// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.studentmanagement.domain;

import com.studentmanagement.domain.Student;
import com.studentmanagement.domain.StudentDataOnDemand;
import com.studentmanagement.domain.Subject;
import com.studentmanagement.domain.SubjectRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SubjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubjectDataOnDemand: @Component;
    
    private Random SubjectDataOnDemand.rnd = new SecureRandom();
    
    private List<Subject> SubjectDataOnDemand.data;
    
    @Autowired
    private StudentDataOnDemand SubjectDataOnDemand.studentDataOnDemand;
    
    @Autowired
    SubjectRepository SubjectDataOnDemand.subjectRepository;
    
    public Subject SubjectDataOnDemand.getNewTransientSubject(int index) {
        Subject obj = new Subject();
        setExamDate(obj, index);
        setGrade(obj, index);
        setIsApproved(obj, index);
        setName(obj, index);
        setStudent(obj, index);
        return obj;
    }
    
    public void SubjectDataOnDemand.setExamDate(Subject obj, int index) {
        Date examDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setExamDate(examDate);
    }
    
    public void SubjectDataOnDemand.setGrade(Subject obj, int index) {
        int grade = index;
        if (grade < 1 || grade > 10) {
            grade = 10;
        }
        obj.setGrade(grade);
    }
    
    public void SubjectDataOnDemand.setIsApproved(Subject obj, int index) {
        Boolean isApproved = Boolean.TRUE;
        obj.setIsApproved(isApproved);
    }
    
    public void SubjectDataOnDemand.setName(Subject obj, int index) {
        String name = "name_" + index;
        if (name.length() > 25) {
            name = name.substring(0, 25);
        }
        obj.setName(name);
    }
    
    public void SubjectDataOnDemand.setStudent(Subject obj, int index) {
        Student student = studentDataOnDemand.getRandomStudent();
        obj.setStudent(student);
    }
    
    public Subject SubjectDataOnDemand.getSpecificSubject(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Subject obj = data.get(index);
        java.lang.Long id = obj.getId();
        return subjectRepository.findOne(id);
    }
    
    public Subject SubjectDataOnDemand.getRandomSubject() {
        init();
        Subject obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return subjectRepository.findOne(id);
    }
    
    public boolean SubjectDataOnDemand.modifySubject(Subject obj) {
        return false;
    }
    
    public void SubjectDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = subjectRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Subject' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.studentmanagement.domain.Subject>();
        for (int i = 0; i < 10; i++) {
            Subject obj = getNewTransientSubject(i);
            try {
                subjectRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            subjectRepository.flush();
            data.add(obj);
        }
    }
    
}
